##########################

LIBNAME := fbcunit

SRCS := fbcunit.bas

HDRS := $(wildcard *.bi)
HDRS += $(wildcard ../inc/*.bi)

DEP_LIBS :=

BASEDIR := ..

include ../library.inc

.PHONY: clean
clean: clean_library
